export const baseKeywords = [
  "Francis Ignacio",
  "Francis",
  "mnemora",
  "francistries.science",
  "portfolio",
  "personal website",
  "resume",
  "projects",
  "blog",
  "speaker",
  "technical writing",
  "software engineer",
  "technical lead",
  "engineering leadership",
  "backend engineer",
  "full-stack",
  "system design",
  "architecture",
  "distributed systems",
  "scalable systems",
  "performance optimization",
  "latency reduction",
  "scalability",
  "reliability",
  "observability",
  "monitoring",
  "logging",
  "tracing",
  "cloud infrastructure",
  "AWS",
  "Kubernetes",
  "Docker",
  "CI/CD",
  "infrastructure",
  "devops",
  "SRE",
  "data-driven",
  "analytics",
  "APIs",
  "REST",
  "GraphQL",
  "TypeScript",
  "JavaScript",
  "Node.js",
  "React",
  "Next.js",
  "OpenAI",
  "AI-powered products",
  "machine learning",
  "ML systems",
  "AI",
  "product engineering",
  "growth",
  "migration",
  "legacy migration",
  "observability",
  "research",
  "academia",
  "education",
  "mentoring",
  "teaching",
  "open-source",
  "accessibility",
  "security",
  "privacy",
  "portfolio site",
]
