import fs from "node:fs/promises"
import path from "node:path"

import matter from "gray-matter"

import { noteFrontmatterSchema, type GeneratedNoteRecord } from "../lib/schema/note"

const notesDirectory = new URL("../contents/notes/", import.meta.url)
const outputDirectory = new URL("../lib/generated/", import.meta.url)
const noteModulesDirectory = new URL("../lib/generated/notes/", import.meta.url)
const indexFile = new URL("../lib/generated/notes.generated.ts", import.meta.url)

function getNoteSlugFromFileName(fileName: string) {
  return path.basename(fileName, path.extname(fileName))
}

function getNoteModuleFileName(slug: string) {
  return `${slug}.ts`
}

function getNoteExportName(slug: string) {
  const normalizedSlug = slug.replace(/[^a-zA-Z0-9]+/g, "_").replace(/^_+|_+$/g, "")
  return `${normalizedSlug || "note"}GeneratedNote`
}

async function getGeneratedNotes(): Promise<GeneratedNoteRecord[]> {
  const entries = await fs.readdir(notesDirectory, { withFileTypes: true })
  const noteFileNames = entries
    .filter((entry) => entry.isFile() && entry.name.endsWith(".mdx"))
    .map((entry) => entry.name)
    .sort((left, right) => left.localeCompare(right))

  return Promise.all(
    noteFileNames.map(async (fileName) => {
      const fileUrl = new URL(fileName, notesDirectory)
      const raw = await fs.readFile(fileUrl, "utf8")
      const { data, content } = matter(raw)

      return {
        slug: getNoteSlugFromFileName(fileName),
        frontmatter: noteFrontmatterSchema.parse(data),
        source: content,
      }
    }),
  )
}

async function removeGeneratedNoteModules() {
  await fs.rm(noteModulesDirectory, { recursive: true, force: true })
  await fs.mkdir(noteModulesDirectory, { recursive: true })
}

async function writeGeneratedNoteModule(note: GeneratedNoteRecord) {
  const moduleFile = new URL(getNoteModuleFileName(note.slug), noteModulesDirectory)
  const moduleContents = `/* This file is generated by scripts/generate-notes.ts. */

import type { GeneratedNoteRecord } from "../../schema/note"

export const ${getNoteExportName(note.slug)}: GeneratedNoteRecord = ${JSON.stringify(note, null, 2)}
`

  await fs.writeFile(moduleFile, moduleContents, "utf8")
}

async function writeGeneratedNotesIndex(notes: GeneratedNoteRecord[]) {
  const imports = notes
    .map((note) => {
      const exportName = getNoteExportName(note.slug)
      const modulePath = `./notes/${note.slug}`
      return `import { ${exportName} } from "${modulePath}"`
    })
    .join("\n")

  const noteExports = notes.map((note) => getNoteExportName(note.slug)).join(", ")
  const indexContents = `/* This file is generated by scripts/generate-notes.ts. */

import type { GeneratedNoteRecord } from "../schema/note"
${imports ? `\n${imports}\n` : "\n"}
export const generatedNotes: GeneratedNoteRecord[] = [${noteExports}]
`

  await fs.writeFile(indexFile, indexContents, "utf8")
}

async function main() {
  const notes = await getGeneratedNotes()

  await fs.mkdir(outputDirectory, { recursive: true })
  await removeGeneratedNoteModules()
  await Promise.all(notes.map((note) => writeGeneratedNoteModule(note)))
  await writeGeneratedNotesIndex(notes)
}

await main()
