// ⚠️ AUTO-GENERATED - DO NOT EDIT
// Generated by: npm run generate:blog
// Date: 2025-10-16T17:09:36.950Z

import type { BlogPost } from "../mdx"

export const BLOG_POSTS: BlogPost[] = [
  {
    "slug": "hello-2",
    "title": "Hello World!",
    "date": "2025-09-28",
    "description": "Welcome to my first blog post",
    "tags": [
      "greetings"
    ],
    "authors": [
      {
        "name": "Francis Ignacio",
        "url": "https://francistries.science",
        "imageUrl": "https://avatars.githubusercontent.com/u/132775768?s=96&v=4"
      }
    ],
    "content": "\nHello World!\n",
    "readingTime": 1
  },
  {
    "slug": "hello-world",
    "title": "Hello World!",
    "date": "2025-09-28",
    "description": "Welcome to my first blog post",
    "tags": [
      "greetings"
    ],
    "authors": [
      {
        "name": "Francis Ignacio",
        "url": "https://francistries.science",
        "imageUrl": "https://avatars.githubusercontent.com/u/132775768?s=96&v=4"
      }
    ],
    "content": "\n# Hello World\n\nThis is my first blog post! Welcome to my personal blog where I'll be sharing my thoughts, experiences, and learnings.\n\n## Why I Started This Blog\n\nI wanted to have a place to document my journey and share knowledge with others.\n\n## What to Expect\n\n- Technical tutorials\n- Personal experiences\n- Project showcases\n- And much more!\n\nStay tuned for more content!\n\n# Hello\n",
    "readingTime": 1
  }
]
