#!/usr/bin/env node
import fs from "fs"
import path from "path"
import matter from "gray-matter"
import { execSync } from "child_process"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const CONTENT_DIR = path.join(__dirname, "..", "content", "notebooks")
const GENERATED_DIR = path.join(__dirname, "..", "lib", "notebooks", "generated")

function getMDXFiles() {
  if (!fs.existsSync(CONTENT_DIR)) {
    return []
  }
  return fs.readdirSync(CONTENT_DIR).filter((file) => file.endsWith(".mdx"))
}

function readMDXFile(filePath) {
  const rawContent = fs.readFileSync(filePath, "utf-8")
  return matter(rawContent)
}

function getAllPosts() {
  const files = getMDXFiles()
  return files.map((file) => {
    const filePath = path.join(CONTENT_DIR, file)
    const { data, content } = readMDXFile(filePath)
    const slug = path.basename(file, ".mdx")

    const wordsPerMinute = 200
    const wordCount = content.split(/\s+/).length
    const readingTime = Math.ceil(wordCount / wordsPerMinute)

    const activeDate = getLastGitCommitDate(filePath) || getFileMtimeIso(filePath)

    return {
      slug,
      title: data.title || "Untitled",
      banner: data.banner || "",
      date: data.date || new Date().toISOString(),
      description: data.description || "",
      tags: data.tags || [],
      authors: data.authors || [],
      active: typeof data.active === "boolean" ? data.active : false,
      activeDate,
      content,
      readingTime,
    }
  })
}

function getLastGitCommitDate(filePath) {
  try {
    const cmd = `git log -1 --format=%cI -- ${escapeShellArg(filePath)}`
    const out = execSync(cmd, { encoding: "utf8" }).trim()
    return out || null
  } catch {
    return null
  }
}

function getFileMtimeIso(filePath) {
  try {
    const stat = fs.statSync(filePath)
    return stat.mtime.toISOString()
  } catch {
    return new Date().toISOString()
  }
}

function escapeShellArg(s) {
  return `'${s.replace(/'/g, `\\'`)}'`
}

const posts = getAllPosts()

if (!fs.existsSync(GENERATED_DIR)) {
  fs.mkdirSync(GENERATED_DIR, { recursive: true })
}

for (const post of posts) {
  const filePath = path.join(GENERATED_DIR, `${post.slug}.ts`)
  const fileContents = `// AUTO-GENERATED - DO NOT EDIT
// Generated by: npm run generate:notebooks
// Date: ${new Date().toISOString()}

import type { NotebookPost } from "../../mdx"

export const post: NotebookPost = ${JSON.stringify(post, null, 2)}

export default post
`
  fs.writeFileSync(filePath, fileContents, "utf-8")
}

const indexPath = path.join(GENERATED_DIR, "_index.ts")
const importLines = posts
  .map((p) => `import ${sanitizeExportName(p.slug)} from "./${p.slug}"`)
  .join("\n")

const namedLines = posts.map((p) => `${sanitizeExportName(p.slug)}`).join(",\n  ")

const indexContents = `// AUTO-GENERATED - DO NOT EDIT
// Barrel file for generated posts
// Generated by: npm run generate:notebooks
// Date: ${new Date().toISOString()}

import type { NotebookPost } from "../../mdx"
${importLines}

export const posts: NotebookPost[] = [
  ${namedLines}
]

export default posts
`

fs.writeFileSync(indexPath, indexContents, "utf-8")

function sanitizeExportName(slug) {
  const s = slug.replace(/[^a-zA-Z0-9_$]/g, "_")
  if (/^[0-9]/.test(s)) return `p_${s}`
  return s
}
