#!/usr/bin/env node
import fs from "fs"
import path from "path"
import matter from "gray-matter"
import { execSync } from "child_process"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const CONTENT_DIR = path.join(__dirname, "..", "content", "notebooks")
const OUTPUT_FILE = path.join(__dirname, "..", "lib", "notebooks", "generated.ts")

function getMDXFiles() {
  if (!fs.existsSync(CONTENT_DIR)) {
    return []
  }
  return fs.readdirSync(CONTENT_DIR).filter((file) => file.endsWith(".mdx"))
}

function readMDXFile(filePath) {
  const rawContent = fs.readFileSync(filePath, "utf-8")
  return matter(rawContent)
}

function getAllPosts() {
  const files = getMDXFiles()
  return files.map((file) => {
    const filePath = path.join(CONTENT_DIR, file)
    const { data, content } = readMDXFile(filePath)
    const slug = path.basename(file, ".mdx")

    const wordsPerMinute = 200
    const wordCount = content.split(/\s+/).length
    const readingTime = Math.ceil(wordCount / wordsPerMinute)

    const activeDate = getLastGitCommitDate(filePath) || getFileMtimeIso(filePath)

    return {
      slug,
      title: data.title || "Untitled",
      banner: data.banner || "",
      date: data.date || new Date().toISOString(),
      description: data.description || "",
      tags: data.tags || [],
      authors: data.authors || [],
      active: typeof data.active === "boolean" ? data.active : false,
      activeDate,
      content,
      readingTime,
    }
  })
}

function getLastGitCommitDate(filePath) {
  try {
    const cmd = `git log -1 --format=%cI -- ${escapeShellArg(filePath)}`
    const out = execSync(cmd, { encoding: "utf8" }).trim()
    return out || null
  } catch {
    return null
  }
}

function getFileMtimeIso(filePath) {
  try {
    const stat = fs.statSync(filePath)
    return stat.mtime.toISOString()
  } catch {
    return new Date().toISOString()
  }
}

function escapeShellArg(s) {
  return `'${s.replace(/'/g, `\\'`)}'`
}

const posts = getAllPosts()

const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by: npm run generate:notebooks
// Date: ${new Date().toISOString()}

import type { NotebookPost } from "../mdx"

export const NOTEBOOK_POSTS: NotebookPost[] = ${JSON.stringify(posts, null, 2)}
`

fs.writeFileSync(OUTPUT_FILE, output, "utf-8")
