#!/usr/bin/env node
import fs from "fs"
import path from "path"
import matter from "gray-matter"
import { fileURLToPath } from "url"

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)
const CONTENT_DIR = path.join(__dirname, "..", "content", "blog")
const OUTPUT_FILE = path.join(__dirname, "..", "lib", "blog", "generated.ts")

console.log("Generating static blog data for Cloudflare...")

function getMDXFiles() {
  if (!fs.existsSync(CONTENT_DIR)) {
    console.error(`Content directory not found: ${CONTENT_DIR}`)
    return []
  }
  return fs.readdirSync(CONTENT_DIR).filter((file) => file.endsWith(".mdx"))
}

function readMDXFile(filePath) {
  const rawContent = fs.readFileSync(filePath, "utf-8")
  return matter(rawContent)
}

function getAllPosts() {
  const files = getMDXFiles()
  return files.map((file) => {
    const filePath = path.join(CONTENT_DIR, file)
    const { data, content } = readMDXFile(filePath)
    const slug = path.basename(file, ".mdx")

    const wordsPerMinute = 200
    const wordCount = content.split(/\s+/).length
    const readingTime = Math.ceil(wordCount / wordsPerMinute)

    return {
      slug,
      title: data.title || "Untitled",
      date: data.date || new Date().toISOString(),
      description: data.description || "",
      tags: data.tags || [],
      authors: data.authors || [],
      content,
      readingTime,
    }
  })
}

const posts = getAllPosts()

const output = `// AUTO-GENERATED - DO NOT EDIT
// Generated by: npm run generate:blog
// Date: ${new Date().toISOString()}

import type { BlogPost } from "../mdx"

export const BLOG_POSTS: BlogPost[] = ${JSON.stringify(posts, null, 2)}
`

fs.writeFileSync(OUTPUT_FILE, output, "utf-8")

const sizeKB = (Buffer.byteLength(output) / 1024).toFixed(2)
console.log(`Generated ${posts.length} blog post(s)`)
console.log(`Bundle size: ${sizeKB} KB`)
console.log(`File: lib/blog/generated.ts`)
