package notes

import (
	"encoding/json"
	"fmt"
	"os"
	"path/filepath"
	"regexp"
	"strings"
)

func WriteGenerated(outputDir string, files []File) error {
	notesDir := filepath.Join(outputDir, "notes")

	if err := os.RemoveAll(notesDir); err != nil {
		return fmt.Errorf("Clean notes output: %w", err)
	}

	if err := os.MkdirAll(notesDir, 0o755); err != nil {
		return fmt.Errorf("Create notes output dir: %w", err)
	}

	importNames := make([]string, 0, len(files))
	for _, file := range files {
		exportName := exportNameForSlug(file.Slug)
		importNames = append(importNames, exportName)

		record := GeneratedRecord{
			Slug:        file.Slug,
			Frontmatter: file.Frontmatter,
			Source:      file.Source,
		}

		if err := writeFile(filepath.Join(notesDir, file.Slug+".ts"), renderNoteFile(exportName, record)); err != nil {
			return fmt.Errorf("Write note file %s: %w", file.Slug, err)
		}
	}

	if err := writeFile(filepath.Join(outputDir, "notes.generated.ts"), renderIndexFile(files, importNames)); err != nil {
		return fmt.Errorf("Write index file: %w", err)
	}

	return nil
}

func renderNoteFile(exportName string, record GeneratedRecord) string {
	payload, err := json.MarshalIndent(record, "", "  ")
	if err != nil {
		panic(err)
	}

	return fmt.Sprintf(`/* This file is generated by apps/generator. */

import type { GeneratedNoteRecord } from "../../schema/note"

export const %s: GeneratedNoteRecord = %s
`, exportName, string(payload))
}

func renderIndexFile(files []File, exportNames []string) string {
	var builder strings.Builder
	builder.WriteString("/* This file is generated by apps/generator. */\n\n")
	builder.WriteString("import type { GeneratedNoteRecord } from \"../schema/note\"\n\n")

	for i, file := range files {
		builder.WriteString(fmt.Sprintf("import { %s } from \"./notes/%s\"\n", exportNames[i], file.Slug))
	}

	builder.WriteString("\nexport const generatedNotes: GeneratedNoteRecord[] = [")
	builder.WriteString(strings.Join(exportNames, ", "))
	builder.WriteString("]\n")

	return builder.String()
}

func writeFile(path string, content string) error {
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("Create dir for %s: %w", path, err)
	}

	if err := os.WriteFile(path, []byte(content), 0o644); err != nil {
		return fmt.Errorf("Write %s: %w", path, err)
	}

	return nil
}

func exportNameForSlug(slug string) string {
	parts := regexp.MustCompile(`[^a-zA-Z0-9]+`).Split(slug, -1)
	var builder strings.Builder
	for i, part := range parts {
		if part == "" {
			continue
		}
		if i == 0 {
			builder.WriteString(strings.ToLower(part[:1]))
			if len(part) > 1 {
				builder.WriteString(part[1:])
			}
			continue
		}
		builder.WriteString(strings.ToUpper(part[:1]))
		if len(part) > 1 {
			builder.WriteString(strings.ToLower(part[1:]))
		}
	}
	builder.WriteString("GeneratedNote")
	return builder.String()
}
